# Generated by Django 3.1.3 on 2020-11-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='alt',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='snp',
            name='chrm',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='snp',
            name='pos',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='snp',
            name='ref',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
