# Generated by Django 3.1.3 on 2020-11-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_auto_20201130_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snp',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='chrm',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='ref',
        ),
    ]
