# Generated by Django 3.1.3 on 2020-12-24 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0004_auto_20201130_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='cell',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
