# Generated by Django 3.1.3 on 2021-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0005_auto_20201224_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp',
            name='alt',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='snp',
            name='chrm',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='snp',
            name='pos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snp',
            name='ref',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
